package FactoryAndData.ExcelTest_Jiudian_JieSuanLiuShui;

import org.testng.annotations.DataProvider;
import org.testng.annotations.Factory;

import CommonFunction.WriterExcelUtil;
import TestScript.ExcelTest_Jiudian_JieSuanLiuShui.CompareContents_Liushui_JieSuanLiuShui;

public class CompareContents_BaseFields {
	
	
	public static String trc_testDate = WriterExcelUtil.getValueFromConf("jiesuan_bill.properties", "trc_date");
	public static String tcc_testDate = WriterExcelUtil.getValueFromConf("jiesuan_bill.properties", "tcc_date");
	public static String elong_testDate = WriterExcelUtil.getValueFromConf("jiesuan_bill.properties", "elong_date");
	public static String zyx_testDate = WriterExcelUtil.getValueFromConf("jiesuan_bill.properties", "zyx_date");
	public static String top_testDate = WriterExcelUtil.getValueFromConf("jiesuan_bill.properties", "top_date");
	public static String cnb_testDate = WriterExcelUtil.getValueFromConf("jiesuan_bill.properties", "cnb_date");
	public static String gta_testDate = WriterExcelUtil.getValueFromConf("jiesuan_bill.properties", "gta_date");
	public static String ctrip_out_testDate = WriterExcelUtil.getValueFromConf("jiesuan_bill.properties", "ctrip_out_date");
	public static String webbeds_testDate = WriterExcelUtil.getValueFromConf("jiesuan_bill.properties", "webbeds_date");
	public static String ctrip_in_testDate = WriterExcelUtil.getValueFromConf("jiesuan_bill.properties", "ctrip_in_date");
	public static String jalan_testDate = WriterExcelUtil.getValueFromConf("jiesuan_bill.properties", "jalan_date");
	
	
	
	
	@DataProvider(name = "results")
	public static Object[][] Data16389() {

		return new Object[][] { 
			
			
			// ctrip_in
			
			{		// 结算
				  "C:\\Users\\gaopan\\Desktop\\已结算流水\\数据准备\\jalan\\"+jalan_testDate+"\\结算流水对账全表.xlsx",
				  "C:\\Users\\gaopan\\Desktop\\已结算流水\\results\\jalan\\baseFields_"+jalan_testDate+".xls",
				  "jiesuan_bill",
				  "bill",
				  "OTA",
				  "流水ID",
				  "订单ID",
				  "OTA订单ID",
				  "流水类型",
				  "业务模式",
				  "订单状态",
				  "入住时间",
				  "离店时间",
				  "成本价",
				  "销售价",
				  "实际销售价",
				  "支付(实收)金额",
				  "佣金比例",
				  "报表收入",
				  "补贴",
				  "补贴：优惠券",
				  "补贴：蜂蜜",
				  "补贴：折扣",
				  "报表费用",
				  "订单日汇率",
				  "应结算金额",
				  //------流水--------
				  "OTA",
				  "流水ID",
				  "订单ID",
				  "OTA订单ID",
				  "流水类型",
				  "业务模式",
				  "订单状态",
				  "入住时间",
				  "离店时间",
				  "成本价-RMB",
				  "销售价",
				  "实际销售价",
				  "支付(实收)金额",
				  "佣金比例",
				  "报表收入",
				  "补贴",
				  "补贴：优惠券",
				  "补贴：蜂蜜",
				  "补贴：折扣",
				  "费用",
				  "订单日汇率",
				  "应结算金额"  
			  },
			
			/*// ctrip_in
			
			{		// 结算
				  "C:\\Users\\gaopan\\Desktop\\已结算流水\\数据准备\\ctrip_in\\"+ctrip_in_testDate+"\\结算流水对账全表.xlsx",
				  "C:\\Users\\gaopan\\Desktop\\已结算流水\\results\\ctrip_in\\baseFields_"+ctrip_in_testDate+".xls",
				  "jiesuan_bill",
				  "bill",
				  "OTA",
				  "流水ID",
				  "订单ID",
				  "OTA订单ID",
				  "流水类型",
				  "业务模式",
				  "订单状态",
				  "入住时间",
				  "离店时间",
				  "成本价",
				  "销售价",
				  "实际销售价",
				  "支付(实收)金额",
				  "佣金比例",
				  "报表收入",
				  "补贴",
				  "补贴：优惠券",
				  "补贴：蜂蜜",
				  "补贴：折扣",
				  "报表费用",
				  "订单日汇率",
				  "应结算金额",
				  //------流水--------
				  "OTA",
				  "流水ID",
				  "订单ID",
				  "OTA订单ID",
				  "流水类型",
				  "业务模式",
				  "订单状态",
				  "入住时间",
				  "离店时间",
				  "成本价-RMB",
				  "销售价",
				  "实际销售价",
				  "支付(实收)金额",
				  "佣金比例",
				  "报表收入",
				  "补贴",
				  "补贴：优惠券",
				  "补贴：蜂蜜",
				  "补贴：折扣",
				  "费用",
				  "订单日汇率",
				  "应结算金额"  
			  },*/
			
			/*// webbeds
			
			{		// 结算
				  "C:\\Users\\gaopan\\Desktop\\已结算流水\\数据准备\\webbeds\\"+webbeds_testDate+"\\结算流水对账全表.xlsx",
				  "C:\\Users\\gaopan\\Desktop\\已结算流水\\results\\webbeds\\baseFields_"+webbeds_testDate+".xls",
				  "jiesuan_bill",
				  "bill",
				  "OTA",
				  "流水ID",
				  "订单ID",
				  "OTA订单ID",
				  "流水类型",
				  "业务模式",
				  "订单状态",
				  "入住时间",
				  "离店时间",
				  "成本价",
				  "销售价",
				  "实际销售价",
				  "支付(实收)金额",
				  "佣金比例",
				  "报表收入",
				  "补贴",
				  "补贴：优惠券",
				  "补贴：蜂蜜",
				  "补贴：折扣",
				  "报表费用",
				  "订单日汇率",
				  "应结算金额",
				  //------流水--------
				  "OTA",
				  "流水ID",
				  "订单ID",
				  "OTA订单ID",
				  "流水类型",
				  "业务模式",
				  "订单状态",
				  "入住时间",
				  "离店时间",
				  "成本价-RMB",
				  "销售价",
				  "实际销售价",
				  "支付(实收)金额",
				  "佣金比例",
				  "报表收入",
				  "补贴",
				  "补贴：优惠券",
				  "补贴：蜂蜜",
				  "补贴：折扣",
				  "费用",
				  "订单日汇率",
				  "应结算金额"  
			  },*/
			
				/*// ctrip_out
	
				{		// 结算
					  "C:\\Users\\gaopan\\Desktop\\已结算流水\\数据准备\\ctrip_out\\"+ctrip_out_testDate+"\\结算流水对账全表.xlsx",
					  "C:\\Users\\gaopan\\Desktop\\已结算流水\\results\\ctrip_out\\baseFields_"+ctrip_out_testDate+".xls",
					  "jiesuan_bill",
					  "bill",
					  "OTA",
					  "流水ID",
					  "订单ID",
					  "OTA订单ID",
					  "流水类型",
					  "业务模式",
					  "订单状态",
					  "入住时间",
					  "离店时间",
					  "成本价",
					  "销售价",
					  "实际销售价",
					  "支付(实收)金额",
					  "佣金比例",
					  "报表收入",
					  "补贴",
					  "补贴：优惠券",
					  "补贴：蜂蜜",
					  "补贴：折扣",
					  "报表费用",
					  "订单日汇率",
					  "应结算金额",
					  //------流水--------
					  "OTA",
					  "流水ID",
					  "订单ID",
					  "OTA订单ID",
					  "流水类型",
					  "业务模式",
					  "订单状态",
					  "入住时间",
					  "离店时间",
					  "成本价-RMB",
					  "销售价",
					  "实际销售价",
					  "支付(实收)金额",
					  "佣金比例",
					  "报表收入",
					  "补贴",
					  "补贴：优惠券",
					  "补贴：蜂蜜",
					  "补贴：折扣",
					  "费用",
					  "订单日汇率",
					  "应结算金额"  
				  },*/
			
			/*// gta
			
			{		// 结算
				  "C:\\Users\\gaopan\\Desktop\\已结算流水\\数据准备\\gta\\"+gta_testDate+"\\结算流水对账全表.xlsx",
				  "C:\\Users\\gaopan\\Desktop\\已结算流水\\results\\gta\\baseFields_"+gta_testDate+".xls",
				  "jiesuan_bill",
				  "bill",
				  "OTA",
				  "流水ID",
				  "订单ID",
				  "OTA订单ID",
				  "流水类型",
				  "业务模式",
				  "订单状态",
				  "入住时间",
				  "离店时间",
				  "成本价",
				  "销售价",
				  "实际销售价",
				  "支付(实收)金额",
				  "佣金比例",
				  "报表收入",
				  "补贴",
				  "补贴：优惠券",
				  "补贴：蜂蜜",
				  "补贴：折扣",
				  "报表费用",
				  "订单日汇率",
				  "应结算金额",
				  //------流水--------
				  "OTA",
				  "流水ID",
				  "订单ID",
				  "OTA订单ID",
				  "流水类型",
				  "业务模式",
				  "订单状态",
				  "入住时间",
				  "离店时间",
				  "成本价-RMB",
				  "销售价",
				  "实际销售价",
				  "支付(实收)金额",
				  "佣金比例",
				  "报表收入",
				  "补贴",
				  "补贴：优惠券",
				  "补贴：蜂蜜",
				  "补贴：折扣",
				  "费用",
				  "订单日汇率",
				  "应结算金额"  
			  },*/
			
			
			/*// cnb
			
			{		// 结算
				  "C:\\Users\\gaopan\\Desktop\\已结算流水\\数据准备\\cnb\\"+cnb_testDate+"\\结算流水对账全表.xlsx",
				  "C:\\Users\\gaopan\\Desktop\\已结算流水\\results\\cnb\\baseFields_"+cnb_testDate+".xls",
				  "jiesuan_bill",
				  "bill",
				  "OTA",
				  "流水ID",
				  "订单ID",
				  "OTA订单ID",
				  "流水类型",
				  "业务模式",
				  "订单状态",
				  "入住时间",
				  "离店时间",
				  "成本价",
				  "销售价",
				  "实际销售价",
				  "支付(实收)金额",
				  "佣金比例",
				  "报表收入",
				  "补贴",
				  "补贴：优惠券",
				  "补贴：蜂蜜",
				  "补贴：折扣",
				  "报表费用",
				  "订单日汇率",
				  "应结算金额",
				  //------流水--------
				  "OTA",
				  "流水ID",
				  "订单ID",
				  "OTA订单ID",
				  "流水类型",
				  "业务模式",
				  "订单状态",
				  "入住时间",
				  "离店时间",
				  "成本价-RMB",
				  "销售价",
				  "实际销售价",
				  "支付(实收)金额",
				  "佣金比例",
				  "报表收入",
				  "补贴",
				  "补贴：优惠券",
				  "补贴：蜂蜜",
				  "补贴：折扣",
				  "费用",
				  "订单日汇率",
				  "应结算金额"  
			  },*/
			
			/*// top
			
			{		// 结算
				  "C:\\Users\\gaopan\\Desktop\\已结算流水\\数据准备\\top\\"+top_testDate+"\\结算流水对账全表.xlsx",
				  "C:\\Users\\gaopan\\Desktop\\已结算流水\\results\\top\\baseFields_"+top_testDate+".xls",
				  "jiesuan_bill",
				  "bill",
				  "OTA",
				  "流水ID",
				  "订单ID",
				  "OTA订单ID",
				  "流水类型",
				  "业务模式",
				  "订单状态",
				  "入住时间",
				  "离店时间",
				  "成本价",
				  "销售价",
				  "实际销售价",
				  "支付(实收)金额",
				  "佣金比例",
				  "报表收入",
				  "补贴",
				  "补贴：优惠券",
				  "补贴：蜂蜜",
				  "补贴：折扣",
				  "报表费用",
				  "订单日汇率",
				  "应结算金额",
				  //------流水--------
				  "OTA",
				  "流水ID",
				  "订单ID",
				  "OTA订单ID",
				  "流水类型",
				  "业务模式",
				  "订单状态",
				  "入住时间",
				  "离店时间",
				  "成本价-RMB",
				  "销售价",
				  "实际销售价",
				  "支付(实收)金额",
				  "佣金比例",
				  "报表收入",
				  "补贴",
				  "补贴：优惠券",
				  "补贴：蜂蜜",
				  "补贴：折扣",
				  "费用",
				  "订单日汇率",
				  "应结算金额"  
			  },*/
			
			
		/*	// zyx
			
			{		// 结算
				  "C:\\Users\\gaopan\\Desktop\\已结算流水\\数据准备\\zyx\\"+zyx_testDate+"\\结算流水对账全表.xlsx",
				  "C:\\Users\\gaopan\\Desktop\\已结算流水\\results\\zyx\\baseFields_"+zyx_testDate+".xls",
				  "jiesuan_bill",
				  "bill",
				  "OTA",
				  "流水ID",
				  "订单ID",
				  "OTA订单ID",
				  "流水类型",
				  "业务模式",
				  "订单状态",
				  "入住时间",
				  "离店时间",
				  "成本价",
				  "销售价",
				  "实际销售价",
				  "支付(实收)金额",
				  "佣金比例",
				  "报表收入",
				  "补贴",
				  "补贴：优惠券",
				  "补贴：蜂蜜",
				  "补贴：折扣",
				  "报表费用",
				  "订单日汇率",
				  "应结算金额",
				  //------流水--------
				  "OTA",
				  "流水ID",
				  "订单ID",
				  "OTA订单ID",
				  "流水类型",
				  "业务模式",
				  "订单状态",
				  "入住时间",
				  "离店时间",
				  "成本价-RMB",
				  "销售价",
				  "实际销售价",
				  "支付(实收)金额",
				  "佣金比例",
				  "报表收入",
				  "补贴",
				  "补贴：优惠券",
				  "补贴：蜂蜜",
				  "补贴：折扣",
				  "费用",
				  "订单日汇率",
				  "应结算金额"  
			  },*/
			
			
				//elong
			
				/*{		// 结算
					  "C:\\Users\\gaopan\\Desktop\\已结算流水\\数据准备\\elong\\"+elong_testDate+"\\结算流水对账全表.xlsx",
					  "C:\\Users\\gaopan\\Desktop\\已结算流水\\results\\elong\\baseFields_"+elong_testDate+".xls",
					  "jiesuan_bill",
					  "bill",
					  "OTA",
					  "流水ID",
					  "订单ID",
					  "OTA订单ID",
					  "流水类型",
					  "业务模式",
					  "订单状态",
					  "入住时间",
					  "离店时间",
					  "成本价",
					  "销售价",
					  "实际销售价",
					  "支付(实收)金额",
					  "佣金比例",
					  "报表收入",
					  "补贴",
					  "补贴：优惠券",
					  "补贴：蜂蜜",
					  "补贴：折扣",
					  "报表费用",
					  "订单日汇率",
					  "应结算金额",
					  //------流水--------
					  "OTA",
					  "流水ID",
					  "订单ID",
					  "OTA订单ID",
					  "流水类型",
					  "业务模式",
					  "订单状态",
					  "入住时间",
					  "离店时间",
					  "成本价-RMB",
					  "销售价",
					  "实际销售价",
					  "支付(实收)金额",
					  "佣金比例",
					  "报表收入",
					  "补贴",
					  "补贴：优惠券",
					  "补贴：蜂蜜",
					  "补贴：折扣",
					  "费用",
					  "订单日汇率",
					  "应结算金额"  
				  },*/
				
				
			/*// tcc
				
				{		// 结算
					  "C:\\Users\\gaopan\\Desktop\\已结算流水\\数据准备\\tcc\\"+tcc_testDate+"\\结算流水对账全表.xlsx",
					  "C:\\Users\\gaopan\\Desktop\\已结算流水\\results\\tcc\\baseFields_"+tcc_testDate+".xls",
					  "jiesuan_bill",
					  "bill",
					  "OTA",
					  "流水ID",
					  "订单ID",
					  "OTA订单ID",
					  "流水类型",
					  "业务模式",
					  "订单状态",
					  "入住时间",
					  "离店时间",
					  "成本价",
					  "销售价",
					  "实际销售价",
					  "支付(实收)金额",
					  "佣金比例",
					  "报表收入",
					  "补贴",
					  "补贴：优惠券",
					  "补贴：蜂蜜",
					  "补贴：折扣",
					  "报表费用",
					  "订单日汇率",
					  "应结算金额",
					  //------流水--------
					  "OTA",
					  "流水ID",
					  "订单ID",
					  "OTA订单ID",
					  "流水类型",
					  "业务模式",
					  "订单状态",
					  "入住时间",
					  "离店时间",
					  "成本价-RMB",
					  "销售价",
					  "实际销售价",
					  "支付(实收)金额",
					  "佣金比例",
					  "报表收入",
					  "补贴",
					  "补贴：优惠券",
					  "补贴：蜂蜜",
					  "补贴：折扣",
					  "费用",
					  "订单日汇率",
					  "应结算金额"  
				  },*/
				
				/*// trc
				{
					  "C:\\Users\\gaopan\\Desktop\\已结算流水\\数据准备\\trc\\"+trc_testDate+"\\结算流水对账全表.xlsx",
					  "C:\\Users\\gaopan\\Desktop\\已结算流水\\results\\trc\\baseFields_"+trc_testDate+".xls",
					  "jiesuan_bill",
					  "bill",
					  "OTA",
					  "流水ID",
					  "订单ID",
					  "OTA订单ID",
					  "流水类型",
					  "业务模式",
					  "订单状态",
					  "入住时间",
					  "离店时间",
					  "成本价",
					  "销售价",
					  "实际销售价",
					  "支付(实收)金额",
					  "佣金比例",
					  "报表收入",
					  "补贴",
					  "补贴：优惠券",
					  "补贴：蜂蜜",
					  "补贴：折扣",
					  "报表费用",
					  "订单日汇率",
					  "应结算金额",
					  //--------------
					  "OTA",
					  "流水ID",
					  "订单ID",
					  "OTA订单ID",
					  "流水类型",
					  "业务模式",
					  "订单状态",
					  "入住时间",
					  "离店时间",
					  "成本价-RMB",
					  "销售价",
					  "实际销售价",
					  "支付(实收)金额",
					  "佣金比例",
					  "报表收入",
					  "补贴",
					  "补贴：优惠券",
					  "补贴：蜂蜜",
					  "补贴：折扣",
					  "费用",
					  "订单日汇率",
					  "应结算金额"  
				  },*/
				
				
		};
	}

	@Factory(dataProvider = "results")
	public Object[] createTest(String sourceFile,
								String destinationFile,
								String sheetName_Jiesuan,
								String sheetName_Liushui,
								String OTA_Jiesuan,
								String liushui_id_Jiesuan,
								String dingdan_id_Jiesuan,
								String OTA_dingdan_id_Jiesuan,
								String liushuileixing_Jiesuan,
								String yewumoshi_Jiesuan,
								String dingdanzhuangtai_Jiesuan,
								String ruzhushijian_Jiesuan,
								String lidianshijian_Jiesuan,
								String chengbenjia_Jiesuan,
								String xiaoshoujia_Jiesuan,
								String shijixiaoshoujia_Jiesuan,
								String zhifushishoujine_Jiesuan,
								String yongjinbili_Jiesuan,
								String baobiaoshouru_Jiesuan,
								String butie_Jiesuan,
								String butie_youhuiquan_Jiesuan,
								String butie_fengmi_Jiesuan,
								String butie_zhekou_Jiesuan,
								String baobiaofeiyong_Jiesuan,
								String dingdanrihuilv_Jiesuan,
								String yingjiesuanjine_Jiesuan, 
								String OTA_Liushui,
								String liushui_id_Liushui,
								String dingdan_id_Liushui,
								String OTA_dingdan_id_Liushui,
								String liushuileixing_Liushui,
								String yewumoshi_Liushui,
								String dingdanzhuangtai_Liushui,
								String ruzhushijian_Liushui,
								String lidianshijian_Liushui,
								String chengbenjia_RMB_Liushui,
								String xiaoshoujia_Liushui,
								String shijixiaoshoujia_Liushui,
								String zhifushishoujine_Liushui,
								String yongjinbili_Liushui,
								String baobiaoshouru_Liushui,
								String butie_Liushui,
								String butie_youhuiquan_Liushui,
								String butie_fengmi_Liushui,
								String butie_zhekou_Liushui,
								String feiyong_Liushui,
								String dingdanrihuilv_Liushui,
								String yingjiesuanjine_Liushui) {

		Object[] tests = new Object[1];

		tests[0] = new CompareContents_Liushui_JieSuanLiuShui(sourceFile,
															  destinationFile,
															  sheetName_Jiesuan,
															  sheetName_Liushui,
															  OTA_Jiesuan,
															  liushui_id_Jiesuan,
															  dingdan_id_Jiesuan,
															  OTA_dingdan_id_Jiesuan,
															  liushuileixing_Jiesuan,
															  yewumoshi_Jiesuan,
															  dingdanzhuangtai_Jiesuan,
															  ruzhushijian_Jiesuan,
															  lidianshijian_Jiesuan,
															  chengbenjia_Jiesuan,
															  xiaoshoujia_Jiesuan,
															  shijixiaoshoujia_Jiesuan,
															  zhifushishoujine_Jiesuan,
															  yongjinbili_Jiesuan,
															  baobiaoshouru_Jiesuan,
															  butie_Jiesuan,
															  butie_youhuiquan_Jiesuan,
															  butie_fengmi_Jiesuan,
															  butie_zhekou_Jiesuan,
															  baobiaofeiyong_Jiesuan,
															  dingdanrihuilv_Jiesuan,
															  yingjiesuanjine_Jiesuan,
															  OTA_Liushui,
															  liushui_id_Liushui,
															  dingdan_id_Liushui,
															  OTA_dingdan_id_Liushui,
															  liushuileixing_Liushui,
															  yewumoshi_Liushui,
															  dingdanzhuangtai_Liushui,
															  ruzhushijian_Liushui,
															  lidianshijian_Liushui,
															  chengbenjia_RMB_Liushui,
															  xiaoshoujia_Liushui,
															  shijixiaoshoujia_Liushui,
															  zhifushishoujine_Liushui,
															  yongjinbili_Liushui,
															  baobiaoshouru_Liushui,
															  butie_Liushui,
															  butie_youhuiquan_Liushui,
															  butie_fengmi_Liushui,
															  butie_zhekou_Liushui,
															  feiyong_Liushui,
															  dingdanrihuilv_Liushui,
															  yingjiesuanjine_Liushui);

		return tests;
	}

	
	
	
	
	

}
